(source gnu)
(source melpa)

(depends-on "color-theme")

(depends-on "auto-complete")
(depends-on "color-moccur")
(depends-on "git-gutter")
(depends-on "magit")
(depends-on "migemo")
(depends-on "popup")
(depends-on "redo+")
(depends-on "smartparens")
(depends-on "smart-compile")
(depends-on "helm")
(depends-on "helm-migemo")
(depends-on "flycheck")
(depends-on "ag")
(depends-on "helm-ag")
(depends-on "rbenv")

(depends-on "haskell-mode")
(depends-on "io-mode")
(depends-on "markdown-mode")
(depends-on "python-mode")
(depends-on "scala-mode2")
(depends-on "csharp-mode")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "coffee-mode")
(depends-on "web-mode")
